/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Information;
import mainboard.MainBoardFrm;

/**
 *
 * @author judy
 */
public class InformationEditFrm extends javax.swing.JDialog {

    /**
     * Creates new form InformationFrm
     */
    private MainBoardFrm main;
    public InformationEditFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Edit the Information");
        main = (MainBoardFrm) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInforTitle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lbPhoneNumber = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbDob = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lbStartWorkFrom = new javax.swing.JLabel();
        lbExe = new javax.swing.JLabel();
        txtExe = new javax.swing.JTextField();
        lbPostion = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        optGender = new javax.swing.JComboBox<>();
        optPosition = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        dateDob = new com.toedter.calendar.JDateChooser();
        dateWorkFrom = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbInforTitle.setText("EDIT THE INFORMATION OF STAFF");

        lbName.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lbPhoneNumber.setText("Phone Number:");

        lbGender.setText("Gender:");

        lbDob.setText("DoB:");

        lbAddress.setText("Address");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lbStartWorkFrom.setText("Start working from:");

        lbExe.setText("Experience (months):");

        lbPostion.setText("Positions:");

        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        optGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        optGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optGenderActionPerformed(evt);
            }
        });

        optPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager" }));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lbID.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbInforTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPostion)
                                    .addComponent(lbPhoneNumber)
                                    .addComponent(lbGender)
                                    .addComponent(lbName)
                                    .addComponent(lbExe)
                                    .addComponent(lbID)
                                    .addComponent(lbDob)
                                    .addComponent(lbStartWorkFrom)
                                    .addComponent(lbAddress)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnAdd)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(optPosition, 0, 230, Short.MAX_VALUE)
                                .addComponent(txtAddress)
                                .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(optGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNumber)
                                .addComponent(dateDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dateWorkFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtExe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInforTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbGender)
                        .addGap(18, 18, 18)
                        .addComponent(lbPhoneNumber)
                        .addGap(12, 12, 12)
                        .addComponent(lbDob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStartWorkFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateWorkFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPostion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void optGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optGenderActionPerformed
    
    // Modify the Add buttion
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = "'", ID = "", address = "", gender = "", position = "";
        int exe = 0;
        long phoneNumber = 0;
        boolean isOK = true;
        
        // Name
        name = txtName.getText();
        if (name.length() == 0 ) {
            JOptionPane.showMessageDialog(rootPane, "Name cannot left blank!");
            isOK = false;
        } else if (name.matches("[^a-zA-Z]+")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid name! Name only have the character!");
            isOK = false;
        }
        
        // ID
        ID = txtID.getText();
        if (!ID.equals("MA1") && !ID.equals("MA2") && !ID.equals("S1") && !ID.equals("S2") && !ID.equals("S3") && !ID.equals("S4") && !ID.equals("S5") ) {
            JOptionPane.showMessageDialog(rootPane, """
                                                    The ID should be MA1 and MA2 for two managers
                                                    S1, S2, S3, S4, S5 for the staff""");
            isOK = false;
        } 

        
        // Phone
        try {
            phoneNumber = Long.parseLong(txtPhoneNumber.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Wrong format of phone numbers!");
            isOK = false;
        }
        if (String.valueOf(phoneNumber).length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Phone number cannot left blank!");
            isOK = false;
        } else if (String.valueOf(phoneNumber).length() != 9) {
            JOptionPane.showMessageDialog(rootPane, "Phone number may have 10 numbers!");
            isOK = false;
        }
        String phoneNumber1 = "0" + phoneNumber;
        
        // Gender
        gender = optGender.getSelectedItem().toString();
        
        // Address
        address = txtAddress.getText();
        if (address.length() == 0 ) {
            JOptionPane.showMessageDialog(rootPane, "Address cannot left blank!");
            isOK = false;
        }
        
        // Position
        position = optPosition.getSelectedItem().toString();
        if (position.equals("Manager") && (ID.matches(".*S.*"))) {
            JOptionPane.showMessageDialog(rootPane, """
                                                    Wrong ID for manager!
                                                    The ID should be start with M with (a number 1 or 2)""");
            isOK = false;
        } else if (position.equals("Staff") && (ID.matches(".*MA.*"))) {
            JOptionPane.showMessageDialog(rootPane, """
                                                    Wrong ID for Staff!
                                                    The ID should be start with S with (a number from 1 to 5)""");
            isOK = false;
        }
        

        
        // DoB
        Date dob = dateDob.getDate();
        
        // Experience
        try {
            exe = Integer.parseInt(txtExe.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Wrong format for experience!");
            isOK = false;
        }
        
        // Start work from
        Date workFrom = dateWorkFrom.getDate();

        if (isOK) {
            Information information = new Information(name, ID, phoneNumber1, gender, dob, address, workFrom, exe, position);
            main.updateInformation(information);
            JOptionPane.showMessageDialog(rootPane, "Successfully edited!");
            this.dispose();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationEditFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationEditFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationEditFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationEditFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InformationEditFrm dialog = new InformationEditFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private com.toedter.calendar.JDateChooser dateDob;
    private com.toedter.calendar.JDateChooser dateWorkFrom;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbDob;
    private javax.swing.JLabel lbExe;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbInforTitle;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbPostion;
    private javax.swing.JLabel lbStartWorkFrom;
    private javax.swing.JComboBox<String> optGender;
    private javax.swing.JComboBox<String> optPosition;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtExe;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
    
    public void setEditData(Information i) {
        txtName.setText(i.getName());
        txtID.setText(i.getID());
        optGender.setSelectedItem(i.getGender());
        txtPhoneNumber.setText(i.getPhoneNumber());
        dateDob.setDate(i.getDoB());
        txtAddress.setText(i.getAddress());
        dateWorkFrom.setDate(i.getWorkFrom());
        txtExe.setText(String.valueOf(i.getExe()));
        optPosition.setSelectedItem(i.getPosition());
    }

}
