/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainboard;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Admin
 */
public class ImportMain extends javax.swing.JFrame {
    private ArrayList<Import>imports;
    private DefaultListModel listImportModel;
    private int Gasoline2 = 1000; 
    private int Diesel2 = 1000;
    private int Lubrocant2 = 1000;
    private int Hydraulic2 = 1000;
    

    /**
     * Creates new form ImportMain
     */
    public ImportMain() {
        initComponents();
        imports = new ArrayList<Import>(); 
        listImportModel = new DefaultListModel(); 
        jList2.setModel(listImportModel);
    }
    public void addimport(){
         Import i = new Import(
                   txtSeller2.getText(),
                   txtDate2.getText(),
                   jComboBox2.getSelectedItem().toString(),
                   txtAmount2.getText(),
                   txtPricePerLiter2.getText(),
                   txtTotalPrice2.getText()
                );
                imports.add(i);
                refreshImportList();
    }
    public void refreshImportList(){
        listImportModel.removeAllElements();
        System.out.println("Remove");  
        for(Import i : imports){
            System.out.println("Add:"+i.getSeller2());
            System.out.println("Add:"+i.getDate2());
            System.out.println("Add:"+i.getType2());
            System.out.println("Add:"+i.getAmount2());  
            System.out.println("Add:"+i.getPricePerLiter2());
            System.out.println("Add:"+i.getTotalPrice2());
            
            listImportModel.addElement("Name:"+i.getSeller2());
            listImportModel.addElement("Date:"+i.getDate2());
            listImportModel.addElement("Type:"+i.getType2());
            listImportModel.addElement("Amount:"+i.getAmount2());
            listImportModel.addElement("Price per Liter:"+i.getPricePerLiter2());
            listImportModel.addElement("Total price:"+i.getTotalPrice2());
            listImportModel.addElement("----------");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeller2 = new javax.swing.JLabel();
        jDate2 = new javax.swing.JLabel();
        jType2 = new javax.swing.JLabel();
        jAmount2 = new javax.swing.JLabel();
        jPricePerLiter2 = new javax.swing.JLabel();
        jTotalPrice2 = new javax.swing.JLabel();
        txtSeller2 = new javax.swing.JTextField();
        txtDate2 = new javax.swing.JTextField();
        txtAmount2 = new javax.swing.JTextField();
        txtPricePerLiter2 = new javax.swing.JTextField();
        txtTotalPrice2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnCalculate2 = new javax.swing.JButton();
        btnProceed2 = new javax.swing.JButton();
        btnXuat2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDieselName2 = new javax.swing.JLabel();
        jDiesel2 = new javax.swing.JProgressBar();
        jLubrocantName2 = new javax.swing.JLabel();
        jLubrocant2 = new javax.swing.JProgressBar();
        jHydraulicName2 = new javax.swing.JLabel();
        jHydraulic2 = new javax.swing.JProgressBar();
        jGasolineName2 = new javax.swing.JLabel();
        jGasoline2 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 242, 251));

        jPanel2.setBackground(new java.awt.Color(241, 242, 251));

        jSeller2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jSeller2.setText("Seller:");

        jDate2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jDate2.setText("Date:");

        jType2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jType2.setText("Type:");

        jAmount2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jAmount2.setText("Amount:");

        jPricePerLiter2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jPricePerLiter2.setText("Price per liter:");

        jTotalPrice2.setFont(new java.awt.Font("Morn-Regular", 1, 12)); // NOI18N
        jTotalPrice2.setText("Total price:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasoline", "Diesel", "Lubrocant", "Hydraulic" }));

        btnCalculate2.setText("Calculate");
        btnCalculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate2ActionPerformed(evt);
            }
        });

        btnProceed2.setText("Proceed");
        btnProceed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceed2ActionPerformed(evt);
            }
        });

        btnXuat2.setText("Xuat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXuat2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(btnProceed2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeller2)
                                    .addComponent(jDate2)
                                    .addComponent(jType2))
                                .addGap(70, 70, 70))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTotalPrice2)
                                    .addComponent(jPricePerLiter2)
                                    .addComponent(jAmount2))
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotalPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtPricePerLiter2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeller2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAmount2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate2)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSeller2)
                    .addComponent(txtSeller2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDate2)
                    .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jType2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAmount2)
                    .addComponent(txtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPricePerLiter2)
                    .addComponent(txtPricePerLiter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate2))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalPrice2)
                    .addComponent(txtTotalPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProceed2)
                    .addComponent(btnXuat2))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(241, 242, 251));

        jDieselName2.setText("Diesel:");

        jDiesel2.setBackground(new java.awt.Color(255, 255, 255));
        jDiesel2.setForeground(new java.awt.Color(0, 204, 51));
        jDiesel2.setMaximum(1000);
        jDiesel2.setValue(1000);
        jDiesel2.setString("1000");
        jDiesel2.setStringPainted(true);

        jLubrocantName2.setText("Lubrocant:");

        jLubrocant2.setBackground(new java.awt.Color(255, 255, 255));
        jLubrocant2.setForeground(new java.awt.Color(0, 204, 51));
        jLubrocant2.setMaximum(1000);
        jLubrocant2.setValue(1000);
        jLubrocant2.setString("1000");
        jLubrocant2.setStringPainted(true);

        jHydraulicName2.setText("Hydraulic");

        jHydraulic2.setBackground(new java.awt.Color(255, 255, 255));
        jHydraulic2.setForeground(new java.awt.Color(0, 204, 51));
        jHydraulic2.setMaximum(1000);
        jHydraulic2.setValue(1000);
        jHydraulic2.setString("1000");
        jHydraulic2.setStringPainted(true);

        jGasolineName2.setText("Gasoline:");

        jGasoline2.setBackground(new java.awt.Color(255, 255, 255));
        jGasoline2.setForeground(new java.awt.Color(0, 204, 51));
        jGasoline2.setMaximum(1000);
        jGasoline2.setValue(1000);
        jGasoline2.setString("1000");
        jGasoline2.setStringPainted(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHydraulic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLubrocant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLubrocantName2)
                    .addComponent(jHydraulicName2)
                    .addComponent(jDiesel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDieselName2)
                    .addComponent(jGasolineName2)
                    .addComponent(jGasoline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jGasolineName2)
                .addGap(18, 18, 18)
                .addComponent(jGasoline2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDieselName2)
                .addGap(18, 18, 18)
                .addComponent(jDiesel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLubrocantName2)
                .addGap(18, 18, 18)
                .addComponent(jLubrocant2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jHydraulicName2)
                .addGap(18, 18, 18)
                .addComponent(jHydraulic2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jScrollPane1.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        int amount = Integer.parseInt(txtAmount2.getText());
        int pricePerLiter = Integer.parseInt(txtPricePerLiter2.getText());

        String totalPrice = String.valueOf(amount*pricePerLiter);
        txtTotalPrice2.setText(totalPrice);
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnProceed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceed2ActionPerformed

        Import i = new Import(
                   txtSeller2.getText(),
                   txtDate2.getText(),
                   jComboBox2.getSelectedItem().toString(),     //NOTED FOR FIXING
                   txtAmount2.getText(),
                   txtPricePerLiter2.getText(),
                   txtTotalPrice2.getText()
                );
                imports.add(i);
                refreshImportList();

        if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Gasoline")){
            if(Gasoline2 > 0 && Gasoline2 + Integer.valueOf(txtAmount2.getText()) <= 1000   )
            {   Gasoline2  = Gasoline2  +  Integer.valueOf(txtAmount2.getText());
                jGasoline2.setValue(Gasoline2);
                jGasoline2.setString(Integer.toString(Gasoline2));
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"The tank is full now!");
            }
        }
        else if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Diesel")){
            if(Diesel2 > 0 && Diesel2 + Integer.valueOf(txtAmount2.getText()) <= 1000)
            {   Diesel2  = Diesel2  +  Integer.valueOf(txtAmount2.getText());
                jDiesel2.setValue(Diesel2);
                jDiesel2.setString(Integer.toString(Diesel2));
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"The tank is full now!");
            }
        }
        else if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Lubrocant")){
            if(Lubrocant2 > 0 && Lubrocant2 + Integer.valueOf(txtAmount2.getText()) <= 1000)
            {   Lubrocant2  = Lubrocant2  +  Integer.valueOf(txtAmount2.getText());
                jLubrocant2.setValue(Lubrocant2);
                jLubrocant2.setString(Integer.toString(Lubrocant2));
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"The tank is full now!");
            }
        }
        else{
            if(Hydraulic2 > 0 && Hydraulic2 + Integer.valueOf(txtAmount2.getText()) <= 1000)
            {   Hydraulic2  = Hydraulic2  +  Integer.valueOf(txtAmount2.getText());
                jHydraulic2.setValue(Hydraulic2);
                jHydraulic2.setString(Integer.toString(Hydraulic2));
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"The tank is full now!");
            }
        }
    }//GEN-LAST:event_btnProceed2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnProceed2;
    private javax.swing.JButton btnXuat2;
    private javax.swing.JLabel jAmount2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jDate2;
    private javax.swing.JProgressBar jDiesel2;
    private javax.swing.JLabel jDieselName2;
    private javax.swing.JProgressBar jGasoline2;
    private javax.swing.JLabel jGasolineName2;
    private javax.swing.JProgressBar jHydraulic2;
    private javax.swing.JLabel jHydraulicName2;
    private javax.swing.JList<String> jList2;
    private javax.swing.JProgressBar jLubrocant2;
    private javax.swing.JLabel jLubrocantName2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPricePerLiter2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSeller2;
    private javax.swing.JLabel jTotalPrice2;
    private javax.swing.JLabel jType2;
    private javax.swing.JTextField txtAmount2;
    private javax.swing.JTextField txtDate2;
    private javax.swing.JTextField txtPricePerLiter2;
    private javax.swing.JTextField txtSeller2;
    private javax.swing.JTextField txtTotalPrice2;
    // End of variables declaration//GEN-END:variables
    
    public void valueChanged(ListSelectionEvent e) {
        int item = jList2.getSelectedIndex();
        if(item >= 0){
            Import i = imports.get(item);
                    txtSeller2.setText(i.getSeller2());
                    txtDate2.setText(i.getDate2().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtAmount2.setText(i.getAmount2());
                    txtPricePerLiter2.setText(i.getPricePerLiter2());
                    txtTotalPrice2.setText(i.getTotalPrice2());
                    
        }           
    }
}

